/**
 * \file gen_version.c
 * \brief generate glc version header based on git status
 * \author Pyry Haulos <pyry.haulos@gmail.com>
 * \date 2007-2008
 * For conditions of distribution and use, see copyright notice in glc.h
 */


#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>

#define SHORTVER_LEN 7

char *extract_version(const char *path)
{
	int result;

	const char *cmd_format = "git --git-dir=\"%s\" rev-parse HEAD";
	size_t cmd_len = strlen(path) + strlen(cmd_format) + 1;

	const char* prefix = "git-";
	size_t prefix_len = strlen(prefix);

	char *version, *cmd = malloc(sizeof(char) * cmd_len);

	snprintf(cmd, cmd_len, cmd_format, path);

	FILE *in = popen(cmd, "r");
	if (!in) {
		fprintf(stderr, "Can't execute %s: %s (%d)\n", cmd, strerror(errno), errno);
		free(cmd);
		return NULL;
	}
	free(cmd);

	version = malloc(sizeof(char) * (SHORTVER_LEN + 1 + prefix_len));
	memcpy(version, prefix, prefix_len);
	result = fread(&version[prefix_len], 1, SHORTVER_LEN, in);

	if (result != SHORTVER_LEN) {
		result = ferror(in);
		fprintf(stderr, "Can't read commit name: %s (%d)\n", strerror(result), result);
		free(version);
		return NULL;
	}

	version[prefix_len + SHORTVER_LEN] = '\0';

	pclose(in);

	return version;
}

int write_version(const char *filename, const char *version)
{
	int result;
	FILE *out = fopen(filename, "w");

	if (!out) {
		fprintf(stderr, "Can't open %s: %s (%d)\n", filename, strerror(errno), errno);
		return errno;
	}

	result = fprintf(out, "#ifndef _VERSION_H\n" \
			   "#define _VERSION_H\n" \
			   "/* generated by %s (compiled %s %s) */\n" \
			   "#define GLC_VERSION \"%s\"\n" \
			   "#endif\n", __FILE__, __DATE__, __TIME__, version);
	if (result < 0) {
		result = ferror(out);
		fprintf(stderr, "Can't write version information: %s (%d)\n", strerror(result), result);
		return result;
	}

	fclose(out);

	return 0;
}

int main(int argc, char *argv[])
{
	if (argc < 3) {
		fprintf(stderr, "%s [git directory] [target] [[version]]\n", argv[0]);
		return EXIT_FAILURE;
	}

	if (argc > 3) {
		if (write_version(argv[2], argv[3])) {
			return EXIT_FAILURE;
		}
	} else {
		char *version = extract_version(argv[1]);
		if (version == NULL) {
			return EXIT_FAILURE;
		}
		if (write_version(argv[2], version)) {
			free(version);
			return EXIT_FAILURE;
		}
		free(version);
	}

	return EXIT_SUCCESS;
}
